In [1]:
import pandas as pd

In [2]:
sp500_filtered = pd.read_csv("sp500_filtered.csv", parse_dates=["date"])
print(sp500_filtered.shape)
sp500_filtered.head()

(2539499, 8)

,date,ticker,open,high,low,close,adj_close,volume
0,2000-01-03,A,46.963894,47.075713,40.180220,42.938419,42.938419,4674353
1,2000-01-04,A,40.627500,41.074778,38.614762,39.658405,39.658405,4765083
2,2000-01-05,A,39.509313,39.658406,35.968387,37.198391,37.198391,5758642
3,2000-01-06,A,36.751110,36.974749,34.663825,35.782013,35.782013,2534434
4,2000-01-07,A,35.222912,39.322934,35.185641,38.763840,38.763840,2819626

In [3]:
# =========================
# FF5
# =========================
ff5 = pd.read_csv(
    "factor data/F-F_Research_Data_5_Factors_2x3_daily.csv",
    skiprows=3
)
ff5 = ff5.rename(columns={ff5.columns[0]: "date"})
ff5 = ff5[ff5["date"].astype(str).str.isnumeric()]
ff5["date"] = pd.to_datetime(ff5["date"], format="%Y%m%d")

# =========================
# Momentum
# =========================
mom = pd.read_csv(
    "factor data/F-F_Momentum_Factor_daily.csv",
    skiprows=13
)
mom = mom.rename(columns={mom.columns[0]: "date"})
mom = mom[mom["date"].astype(str).str.isnumeric()]
mom["date"] = pd.to_datetime(mom["date"], format="%Y%m%d")

# =========================
# Industry 49
# =========================
ind49 = pd.read_csv(
    "factor data/49_Industry_Portfolios_Daily.csv",
    skiprows=9
)
ind49 = ind49.rename(columns={ind49.columns[0]: "date"})
ind49 = ind49[ind49["date"].astype(str).str.isnumeric()]
ind49["date"] = pd.to_datetime(ind49["date"], format="%Y%m%d")

/var/folders/l6/qn_dxw8j00x3g2ft_6s4sz4w0000gn/T/ipykernel_13954/4037404792.py:26: DtypeWarning: Columns (0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49) have mixed types. Specify dtype option on import or set low_memory=False.
  ind49 = pd.read_csv(

In [4]:
#Trim everything starting from 2005.
start_date = "2005-01-01"
end_date = "2026-02-27"

sp500_filtered = sp500_filtered[
    (sp500_filtered["date"] >= start_date) & 
    (sp500_filtered["date"] <= end_date)
]

ff5 = ff5[
    (ff5["date"] >= start_date) & 
    (ff5["date"] <= end_date)
]

mom = mom[
    (mom["date"] >= start_date) & 
    (mom["date"] <= end_date)
]

ind49 = ind49[
    (ind49["date"] >= start_date) & 
    (ind49["date"] <= end_date)
]

In [5]:
# Use the most recent 20 years' data
print("SP500:", sp500_filtered ["date"].min(), sp500_filtered ["date"].max())
print("FF5:", ff5["date"].min(), ff5["date"].max())
print("MOM:", mom["date"].min(), mom["date"].max())
print("IND49:", ind49["date"].min(), ind49["date"].max())

SP500: 2005-01-03 00:00:00 2026-02-27 00:00:00
FF5: 2005-01-03 00:00:00 2026-02-27 00:00:00
MOM: 2005-01-03 00:00:00 2026-02-27 00:00:00
IND49: 2005-01-03 00:00:00 2026-02-27 00:00:00

In [6]:
sp500 = sp500_filtered.copy()

sp500["ret"] = sp500.groupby("ticker")["adj_close"].pct_change()

sp500["y"] = sp500.groupby("ticker")["ret"].shift(-1)

In [7]:
ind49

,date,Agric,Food,Soda,Beer,Smoke,Toys,Fun,Books,Hshld,...,Boxes,Trans,Whlsl,Rtail,Meals,Banks,Insur,RlEst,Fin,Other
20868,2005-01-03,-0.53,-1.12,-0.04,-0.32,-0.73,-2.73,-0.72,-1.13,-0.55,...,-0.84,-1.21,-1.57,0.08,-0.94,-0.53,-0.55,-0.80,-0.60,-0.26
20869,2005-01-04,-1.87,-0.32,-0.96,-1.01,0.56,-0.76,-1.38,-0.38,-1.12,...,-1.89,-2.17,-1.84,-1.13,-0.46,-1.04,-0.45,-1.93,-1.50,-1.34
20870,2005-01-05,-1.08,-0.35,-1.07,-0.69,-0.18,-1.40,-0.44,-0.50,-0.02,...,-2.07,-0.63,-0.89,0.00,-0.96,-0.37,0.19,-2.75,-0.54,-0.55
20871,2005-01-06,-0.06,0.22,0.83,0.27,-0.58,0.44,0.92,0.70,0.70,...,0.35,0.28,0.54,-0.10,1.01,0.33,0.48,0.56,1.26,0.64
20872,2005-01-07,-0.54,0.33,-0.39,0.27,1.34,-1.43,-0.60,-0.16,0.70,...,-0.80,-0.50,-0.66,-0.03,-0.23,-0.65,-0.41,0.41,-0.46,-0.05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52377,2026-02-23,-2.31,-1.03,-0.03,-0.89,-0.68,-3.33,-3.45,-2.12,-2.57,...,-1.55,-3.26,-2.14,-3.05,-2.34,-3.61,-2.13,-2.73,-2.61,-3.66
52378,2026-02-24,0.5,1.46,1.4,2.11,-2.34,1.62,0.2,0.55,0.56,...,0.48,0.97,0.47,-0.04,0.35,0.22,0.86,0.24,1.14,2.43
52379,2026-02-25,-0.84,0.26,0.52,-4.41,3.82,-0.21,5.87,2.28,0.06,...,-2.04,0.17,0.15,-0.41,1.5,1.93,1.41,0.36,1.88,0.81
52380,2026-02-26,1.55,-0.31,-0.13,0.88,-0.05,0.84,2.29,-2.57,1.0,...,0.07,2.37,0.26,1.65,2.65,0.41,0.98,4.49,0.84,0.02
52381,2026-02-27,-0.55,0.16,-0.21,-0.99,-2.63,-1.79,-0.43,0.41,-1.86,...,0.78,-1.42,-0.2,-1.65,-1.47,-3.54,-0.83,0.4,-2.53,-1.46

In [8]:
sp500 = sp500.merge(ff5, on="date", how="left")
sp500 = sp500.merge(mom, on="date", how="left")

In [9]:
sp500["mom_5"] = sp500.groupby("ticker")["ret"].rolling(5).mean().reset_index(0, drop=True)
sp500["vol_20"] = sp500.groupby("ticker")["ret"].rolling(20).std().reset_index(0, drop=True)

In [10]:
sp500.columns

Index(['date', 'ticker', 'open', 'high', 'low', 'close', 'adj_close', 'volume',
       'ret', 'y', 'Mkt-RF', 'SMB', 'HML', 'RMW', 'CMA', 'RF', 'Mom', 'mom_5',
       'vol_20'],
      dtype='object')

In [11]:
feature_cols = [
    "mom_5", "vol_20",
    "Mkt-RF", "SMB", "HML", "RMW", "CMA", "Mom"
]

In [12]:
#Constructing the Covariance Matrix
returns_pivot = sp500.pivot(index="date", columns="ticker", values="ret")

V_dict = {}
window = 60

for i in range(window, len(returns_pivot)):
    date = returns_pivot.index[i]
    V_dict[date] = returns_pivot.iloc[i-window:i].cov()

In [13]:
#Constructing IPO Data
data = []

for date in sp500["date"].unique():
    df_t = sp500[sp500["date"] == date]

    if date not in V_dict:
        continue

    df_t = df_t.dropna(subset=["y"] + feature_cols)

    if len(df_t) < 50:
        continue

    tickers = df_t["ticker"]

    X = df_t[feature_cols].values
    y = df_t["y"].values
    V = V_dict[date].loc[tickers, tickers].values

    data.append((X, y, V))

In [14]:
from sklearn.linear_model import LinearRegression
import numpy as np

def solve_mvo(mu, V, lam=1.0):
    return np.linalg.solve(lam * V, mu)

results = []

for X, y, V in data[:200]:  # 先跑一点
    model = LinearRegression().fit(X, y)
    mu = model.predict(X)

    z = solve_mvo(mu, V)
    ret = z @ y

    results.append(ret)

print("Mean return:", np.mean(results))

Mean return: -2.7356590764370372e+16